-- Multilingual Vamsha relationship lexicon.
-- Generated from Family_Relationship_Words-languages.numbers.

alter table public.relationship_terms
  add column if not exists canonical_code text,
  add column if not exists language_tag text,
  add column if not exists generation text,
  add column if not exists variants text[] not null default array[]::text[],
  add column if not exists source_name text,
  add column if not exists source_type text not null default 'manual',
  add column if not exists updated_at timestamptz not null default now();

update public.relationship_terms
set canonical_code = lower(regexp_replace(canonical_meaning, '[^a-zA-Z0-9]+', '_', 'g'))
where canonical_code is null;

update public.relationship_terms
set language_tag = case language
  when 'Tamil' then 'ta-IN'
  when 'Malayalam' then 'ml-IN'
  when 'Telugu' then 'te-IN'
  when 'Kannada' then 'kn-IN'
  when 'Hindi' then 'hi-IN'
  else 'und'
end
where language_tag is null;

alter table public.relationship_terms
  alter column canonical_code set not null,
  alter column language_tag set not null;

create unique index if not exists relationship_terms_code_language_term_uidx
  on public.relationship_terms (canonical_code, language_tag, term);

insert into public.relationship_terms (
  term,
  canonical_meaning,
  canonical_code,
  language,
  language_tag,
  generation,
  variants,
  source_name,
  source_type
)
values
  ('Muppaṭṭakkārar', 'Great-great-grandfather', 'great_great_grandfather', 'Tamil', 'ta-IN', 'Elder Generation', array['Muppaṭṭakkārar', 'Mūṭāttaṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muttachan (avan avan appan)', 'Great-great-grandfather', 'great_great_grandfather', 'Malayalam', 'ml-IN', 'Elder Generation', array['Muttachan (avan avan appan)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muddu Tāṭayya', 'Great-great-grandfather', 'great_great_grandfather', 'Telugu', 'te-IN', 'Elder Generation', array['Muddu Tāṭayya']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muddajja', 'Great-great-grandfather', 'great_great_grandfather', 'Kannada', 'kn-IN', 'Elder Generation', array['Muddajja']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pardada ka baap (Pūrvaj)', 'Great-great-grandfather', 'great_great_grandfather', 'Hindi', 'hi-IN', 'Elder Generation', array['Pardada ka baap (Pūrvaj)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muppaṭṭi', 'Great-great-grandmother', 'great_great_grandmother', 'Tamil', 'ta-IN', 'Elder Generation', array['Muppaṭṭi', 'Mūṭātti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muttassi (avan avan amma)', 'Great-great-grandmother', 'great_great_grandmother', 'Malayalam', 'ml-IN', 'Elder Generation', array['Muttassi (avan avan amma)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muddu Nānamma', 'Great-great-grandmother', 'great_great_grandmother', 'Telugu', 'te-IN', 'Elder Generation', array['Muddu Nānamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muddajji', 'Great-great-grandmother', 'great_great_grandmother', 'Kannada', 'kn-IN', 'Elder Generation', array['Muddajji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pardadi ki maa (Pūrvaj)', 'Great-great-grandmother', 'great_great_grandmother', 'Hindi', 'hi-IN', 'Elder Generation', array['Pardadi ki maa (Pūrvaj)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muppaṭṭanār', 'Great-grandfather (paternal)', 'great_grandfather_paternal', 'Tamil', 'ta-IN', 'Elder Generation', array['Muppaṭṭanār', 'Koṭṭanār']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appappan', 'Great-grandfather (paternal)', 'great_grandfather_paternal', 'Malayalam', 'ml-IN', 'Elder Generation', array['Appappan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pedda Tāṭayya', 'Great-grandfather (paternal)', 'great_grandfather_paternal', 'Telugu', 'te-IN', 'Elder Generation', array['Pedda Tāṭayya', 'Muttāṭa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appa-appa', 'Great-grandfather (paternal)', 'great_grandfather_paternal', 'Kannada', 'kn-IN', 'Elder Generation', array['Appa-appa', 'Pedda-ajja']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pardada', 'Great-grandfather (paternal)', 'great_grandfather_paternal', 'Hindi', 'hi-IN', 'Elder Generation', array['Pardada']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Muppaṭṭi', 'Great-grandmother (paternal)', 'great_grandmother_paternal', 'Tamil', 'ta-IN', 'Elder Generation', array['Muppaṭṭi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appamma', 'Great-grandmother (paternal)', 'great_grandmother_paternal', 'Malayalam', 'ml-IN', 'Elder Generation', array['Appamma', 'Koṭṭamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pedda Nānamma', 'Great-grandmother (paternal)', 'great_grandmother_paternal', 'Telugu', 'te-IN', 'Elder Generation', array['Pedda Nānamma', 'Muttāṭi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appa-ajji', 'Great-grandmother (paternal)', 'great_grandmother_paternal', 'Kannada', 'kn-IN', 'Elder Generation', array['Appa-ajji', 'Pedda-ajji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pardadi', 'Great-grandmother (paternal)', 'great_grandmother_paternal', 'Hindi', 'hi-IN', 'Elder Generation', array['Pardadi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aṇṇāttaṉ', 'Great-grandfather (maternal)', 'great_grandfather_maternal', 'Tamil', 'ta-IN', 'Elder Generation', array['Aṇṇāttaṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammaman appa', 'Great-grandfather (maternal)', 'great_grandfather_maternal', 'Malayalam', 'ml-IN', 'Elder Generation', array['Ammaman appa', 'Muttāppan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammamma Tāṭayya', 'Great-grandfather (maternal)', 'great_grandfather_maternal', 'Telugu', 'te-IN', 'Elder Generation', array['Ammamma Tāṭayya']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tāyi-appa', 'Great-grandfather (maternal)', 'great_grandfather_maternal', 'Kannada', 'kn-IN', 'Elder Generation', array['Tāyi-appa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Nana ka baap', 'Great-grandfather (maternal)', 'great_grandfather_maternal', 'Hindi', 'hi-IN', 'Elder Generation', array['Nana ka baap']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Āttacci', 'Great-grandmother (maternal)', 'great_grandmother_maternal', 'Tamil', 'ta-IN', 'Elder Generation', array['Āttacci', 'Aṇṇātti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammumma amma', 'Great-grandmother (maternal)', 'great_grandmother_maternal', 'Malayalam', 'ml-IN', 'Elder Generation', array['Ammumma amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammamma Nānamma', 'Great-grandmother (maternal)', 'great_grandmother_maternal', 'Telugu', 'te-IN', 'Elder Generation', array['Ammamma Nānamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tāyi-ajji', 'Great-grandmother (maternal)', 'great_grandmother_maternal', 'Kannada', 'kn-IN', 'Elder Generation', array['Tāyi-ajji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Nani ki maa', 'Great-grandmother (maternal)', 'great_grandmother_maternal', 'Hindi', 'hi-IN', 'Elder Generation', array['Nani ki maa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tāttā', 'Grandfather (paternal)', 'grandfather_paternal', 'Tamil', 'ta-IN', 'Elder Generation', array['Tāttā', 'Paṭṭi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appappan', 'Grandfather (paternal)', 'grandfather_paternal', 'Malayalam', 'ml-IN', 'Elder Generation', array['Appappan', 'Tātan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tāṭayya (Babayya)', 'Grandfather (paternal)', 'grandfather_paternal', 'Telugu', 'te-IN', 'Elder Generation', array['Tāṭayya (Babayya)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ajja', 'Grandfather (paternal)', 'grandfather_paternal', 'Kannada', 'kn-IN', 'Elder Generation', array['Ajja', 'Tāta']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Dada', 'Grandfather (paternal)', 'grandfather_paternal', 'Hindi', 'hi-IN', 'Elder Generation', array['Dada', 'Nana (paternal)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pāṭṭi', 'Grandmother (paternal)', 'grandmother_paternal', 'Tamil', 'ta-IN', 'Elder Generation', array['Pāṭṭi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appamma', 'Grandmother (paternal)', 'grandmother_paternal', 'Malayalam', 'ml-IN', 'Elder Generation', array['Appamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Nānamma (Avva)', 'Grandmother (paternal)', 'grandmother_paternal', 'Telugu', 'te-IN', 'Elder Generation', array['Nānamma (Avva)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ajji', 'Grandmother (paternal)', 'grandmother_paternal', 'Kannada', 'kn-IN', 'Elder Generation', array['Ajji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Dadi', 'Grandmother (paternal)', 'grandmother_paternal', 'Hindi', 'hi-IN', 'Elder Generation', array['Dadi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tāttā (tāymanai)', 'Grandfather (maternal)', 'grandfather_maternal', 'Tamil', 'ta-IN', 'Elder Generation', array['Tāttā (tāymanai)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammapan', 'Grandfather (maternal)', 'grandfather_maternal', 'Malayalam', 'ml-IN', 'Elder Generation', array['Ammapan', 'Māmman']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammamma Tāṭayya', 'Grandfather (maternal)', 'grandfather_maternal', 'Telugu', 'te-IN', 'Elder Generation', array['Ammamma Tāṭayya', 'Thāṭa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tāyi-ajja', 'Grandfather (maternal)', 'grandfather_maternal', 'Kannada', 'kn-IN', 'Elder Generation', array['Tāyi-ajja']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Nana', 'Grandfather (maternal)', 'grandfather_maternal', 'Hindi', 'hi-IN', 'Elder Generation', array['Nana']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Āttai pāṭṭi', 'Grandmother (maternal)', 'grandmother_maternal', 'Tamil', 'ta-IN', 'Elder Generation', array['Āttai pāṭṭi', 'Māmān pāṭṭi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammumma', 'Grandmother (maternal)', 'grandmother_maternal', 'Malayalam', 'ml-IN', 'Elder Generation', array['Ammumma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammamma', 'Grandmother (maternal)', 'grandmother_maternal', 'Telugu', 'te-IN', 'Elder Generation', array['Ammamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tāyi-ajji', 'Grandmother (maternal)', 'grandmother_maternal', 'Kannada', 'kn-IN', 'Elder Generation', array['Tāyi-ajji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Nani', 'Grandmother (maternal)', 'grandmother_maternal', 'Hindi', 'hi-IN', 'Elder Generation', array['Nani']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appā', 'Father', 'father', 'Tamil', 'ta-IN', 'Parent Generation', array['Appā', 'Appa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Achan', 'Father', 'father', 'Malayalam', 'ml-IN', 'Parent Generation', array['Achan', 'Appan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Naanna', 'Father', 'father', 'Telugu', 'te-IN', 'Parent Generation', array['Naanna', 'Nāyanā']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appa', 'Father', 'father', 'Kannada', 'kn-IN', 'Parent Generation', array['Appa', 'Tande']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pitaji', 'Father', 'father', 'Hindi', 'hi-IN', 'Parent Generation', array['Pitaji', 'Papa', 'Bapu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammā', 'Mother', 'mother', 'Tamil', 'ta-IN', 'Parent Generation', array['Ammā', 'Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Amma', 'Mother', 'mother', 'Malayalam', 'ml-IN', 'Parent Generation', array['Amma', 'Ammachi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammā', 'Mother', 'mother', 'Telugu', 'te-IN', 'Parent Generation', array['Ammā', 'Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Amma', 'Mother', 'mother', 'Kannada', 'kn-IN', 'Parent Generation', array['Amma', 'Tayi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Maa', 'Mother', 'mother', 'Hindi', 'hi-IN', 'Parent Generation', array['Maa', 'Maaji', 'Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Periyappa', 'Paternal Uncle (father''s elder brother)', 'paternal_uncle_fathers_elder_brother', 'Tamil', 'ta-IN', 'Parent Generation', array['Periyappa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Valiachhan', 'Paternal Uncle (father''s elder brother)', 'paternal_uncle_fathers_elder_brother', 'Malayalam', 'ml-IN', 'Parent Generation', array['Valiachhan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pedda Naanna', 'Paternal Uncle (father''s elder brother)', 'paternal_uncle_fathers_elder_brother', 'Telugu', 'te-IN', 'Parent Generation', array['Pedda Naanna', 'Peddabba']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Dodda Appa', 'Paternal Uncle (father''s elder brother)', 'paternal_uncle_fathers_elder_brother', 'Kannada', 'kn-IN', 'Parent Generation', array['Dodda Appa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Taauji', 'Paternal Uncle (father''s elder brother)', 'paternal_uncle_fathers_elder_brother', 'Hindi', 'hi-IN', 'Parent Generation', array['Taauji', 'Tau']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Periyamma', 'Paternal Aunt (father''s elder brother''s wife)', 'paternal_aunt_fathers_elder_brothers_wife', 'Tamil', 'ta-IN', 'Parent Generation', array['Periyamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Valiaamma', 'Paternal Aunt (father''s elder brother''s wife)', 'paternal_aunt_fathers_elder_brothers_wife', 'Malayalam', 'ml-IN', 'Parent Generation', array['Valiaamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pedda Amma', 'Paternal Aunt (father''s elder brother''s wife)', 'paternal_aunt_fathers_elder_brothers_wife', 'Telugu', 'te-IN', 'Parent Generation', array['Pedda Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Dodda Amma', 'Paternal Aunt (father''s elder brother''s wife)', 'paternal_aunt_fathers_elder_brothers_wife', 'Kannada', 'kn-IN', 'Parent Generation', array['Dodda Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Taai', 'Paternal Aunt (father''s elder brother''s wife)', 'paternal_aunt_fathers_elder_brothers_wife', 'Hindi', 'hi-IN', 'Parent Generation', array['Taai']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ciṭṭappa', 'Paternal Uncle (father''s younger brother)', 'paternal_uncle_fathers_younger_brother', 'Tamil', 'ta-IN', 'Parent Generation', array['Ciṭṭappa', 'Chittappa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Cheriachhan', 'Paternal Uncle (father''s younger brother)', 'paternal_uncle_fathers_younger_brother', 'Malayalam', 'ml-IN', 'Parent Generation', array['Cheriachhan', 'Ithiachhan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Cinna Naanna', 'Paternal Uncle (father''s younger brother)', 'paternal_uncle_fathers_younger_brother', 'Telugu', 'te-IN', 'Parent Generation', array['Cinna Naanna', 'Baabai']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chikka Appa', 'Paternal Uncle (father''s younger brother)', 'paternal_uncle_fathers_younger_brother', 'Kannada', 'kn-IN', 'Parent Generation', array['Chikka Appa']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chacha', 'Paternal Uncle (father''s younger brother)', 'paternal_uncle_fathers_younger_brother', 'Hindi', 'hi-IN', 'Parent Generation', array['Chacha', 'Kaka']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ciṭṭi', 'Paternal Aunt (father''s younger bro''s wife)', 'paternal_aunt_fathers_younger_bros_wife', 'Tamil', 'ta-IN', 'Parent Generation', array['Ciṭṭi', 'Chitti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Cheriaamma', 'Paternal Aunt (father''s younger bro''s wife)', 'paternal_aunt_fathers_younger_bros_wife', 'Malayalam', 'ml-IN', 'Parent Generation', array['Cheriaamma', 'Ithiamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Cinna Amma', 'Paternal Aunt (father''s younger bro''s wife)', 'paternal_aunt_fathers_younger_bros_wife', 'Telugu', 'te-IN', 'Parent Generation', array['Cinna Amma', 'Baava Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chikka Amma', 'Paternal Aunt (father''s younger bro''s wife)', 'paternal_aunt_fathers_younger_bros_wife', 'Kannada', 'kn-IN', 'Parent Generation', array['Chikka Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chachi', 'Paternal Aunt (father''s younger bro''s wife)', 'paternal_aunt_fathers_younger_bros_wife', 'Hindi', 'hi-IN', 'Parent Generation', array['Chachi', 'Kaki']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aṭṭai', 'Paternal Aunt (father''s sister)', 'paternal_aunt_fathers_sister', 'Tamil', 'ta-IN', 'Parent Generation', array['Aṭṭai', 'Attai']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appante chechi', 'Paternal Aunt (father''s sister)', 'paternal_aunt_fathers_sister', 'Malayalam', 'ml-IN', 'Parent Generation', array['Appante chechi', 'Aniyathi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Naanna Akka', 'Paternal Aunt (father''s sister)', 'paternal_aunt_fathers_sister', 'Telugu', 'te-IN', 'Parent Generation', array['Naanna Akka', 'Naayana Akka (Pinni)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Atte', 'Paternal Aunt (father''s sister)', 'paternal_aunt_fathers_sister', 'Kannada', 'kn-IN', 'Parent Generation', array['Atte', 'Atthe']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bua', 'Paternal Aunt (father''s sister)', 'paternal_aunt_fathers_sister', 'Hindi', 'hi-IN', 'Parent Generation', array['Bua', 'Foi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aṭṭaṉ', 'Paternal Uncle (father''s sister''s husband)', 'paternal_uncle_fathers_sisters_husband', 'Tamil', 'ta-IN', 'Parent Generation', array['Aṭṭaṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appante chechi bhartav', 'Paternal Uncle (father''s sister''s husband)', 'paternal_uncle_fathers_sisters_husband', 'Malayalam', 'ml-IN', 'Parent Generation', array['Appante chechi bhartav']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Baava', 'Paternal Uncle (father''s sister''s husband)', 'paternal_uncle_fathers_sisters_husband', 'Telugu', 'te-IN', 'Parent Generation', array['Baava', 'Bava Gāru']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mava', 'Paternal Uncle (father''s sister''s husband)', 'paternal_uncle_fathers_sisters_husband', 'Kannada', 'kn-IN', 'Parent Generation', array['Mava', 'Atteya ganda']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Fufaji', 'Paternal Uncle (father''s sister''s husband)', 'paternal_uncle_fathers_sisters_husband', 'Hindi', 'hi-IN', 'Parent Generation', array['Fufaji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmā', 'Maternal Uncle (mother''s brother)', 'maternal_uncle_mothers_brother', 'Tamil', 'ta-IN', 'Parent Generation', array['Māmā', 'Mama']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammaavan', 'Maternal Uncle (mother''s brother)', 'maternal_uncle_mothers_brother', 'Malayalam', 'ml-IN', 'Parent Generation', array['Ammaavan', 'Māman']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmayya', 'Maternal Uncle (mother''s brother)', 'maternal_uncle_mothers_brother', 'Telugu', 'te-IN', 'Parent Generation', array['Māmayya', 'Maamayyā']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mava', 'Maternal Uncle (mother''s brother)', 'maternal_uncle_mothers_brother', 'Kannada', 'kn-IN', 'Parent Generation', array['Mava', 'Mama']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mama', 'Maternal Uncle (mother''s brother)', 'maternal_uncle_mothers_brother', 'Hindi', 'hi-IN', 'Parent Generation', array['Mama', 'Mamu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmi', 'Maternal Aunt (mother''s brother''s wife)', 'maternal_aunt_mothers_brothers_wife', 'Tamil', 'ta-IN', 'Parent Generation', array['Māmi', 'Mami']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammaavan bharya', 'Maternal Aunt (mother''s brother''s wife)', 'maternal_aunt_mothers_brothers_wife', 'Malayalam', 'ml-IN', 'Parent Generation', array['Ammaavan bharya', 'Māmi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmamma', 'Maternal Aunt (mother''s brother''s wife)', 'maternal_aunt_mothers_brothers_wife', 'Telugu', 'te-IN', 'Parent Generation', array['Māmamma', 'Peddamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Maami', 'Maternal Aunt (mother''s brother''s wife)', 'maternal_aunt_mothers_brothers_wife', 'Kannada', 'kn-IN', 'Parent Generation', array['Maami']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mami', 'Maternal Aunt (mother''s brother''s wife)', 'maternal_aunt_mothers_brothers_wife', 'Hindi', 'hi-IN', 'Parent Generation', array['Mami', 'Maami']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Periyamma', 'Maternal Aunt (mother''s elder sister)', 'maternal_aunt_mothers_elder_sister', 'Tamil', 'ta-IN', 'Parent Generation', array['Periyamma', 'Peria Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Valiamma (ammante chechi)', 'Maternal Aunt (mother''s elder sister)', 'maternal_aunt_mothers_elder_sister', 'Malayalam', 'ml-IN', 'Parent Generation', array['Valiamma (ammante chechi)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Peddamma', 'Maternal Aunt (mother''s elder sister)', 'maternal_aunt_mothers_elder_sister', 'Telugu', 'te-IN', 'Parent Generation', array['Peddamma', 'Pedda Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Dodda Amma', 'Maternal Aunt (mother''s elder sister)', 'maternal_aunt_mothers_elder_sister', 'Kannada', 'kn-IN', 'Parent Generation', array['Dodda Amma', 'Doddamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Badi Mausi', 'Maternal Aunt (mother''s elder sister)', 'maternal_aunt_mothers_elder_sister', 'Hindi', 'hi-IN', 'Parent Generation', array['Badi Mausi', 'Taai']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ciṭṭi', 'Maternal Aunt (mother''s younger sister)', 'maternal_aunt_mothers_younger_sister', 'Tamil', 'ta-IN', 'Parent Generation', array['Ciṭṭi', 'Chitti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Cheriamma (ammante aniyathi)', 'Maternal Aunt (mother''s younger sister)', 'maternal_aunt_mothers_younger_sister', 'Malayalam', 'ml-IN', 'Parent Generation', array['Cheriamma (ammante aniyathi)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Cinna Amma', 'Maternal Aunt (mother''s younger sister)', 'maternal_aunt_mothers_younger_sister', 'Telugu', 'te-IN', 'Parent Generation', array['Cinna Amma', 'Pinni']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chikka Amma', 'Maternal Aunt (mother''s younger sister)', 'maternal_aunt_mothers_younger_sister', 'Kannada', 'kn-IN', 'Parent Generation', array['Chikka Amma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mausi', 'Maternal Aunt (mother''s younger sister)', 'maternal_aunt_mothers_younger_sister', 'Hindi', 'hi-IN', 'Parent Generation', array['Mausi', 'Choti Mausi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmā (ciṭṭappa)', 'Maternal Uncle (mother''s sister''s husband)', 'maternal_uncle_mothers_sisters_husband', 'Tamil', 'ta-IN', 'Parent Generation', array['Māmā (ciṭṭappa)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammaavan (cheriamma bhartav)', 'Maternal Uncle (mother''s sister''s husband)', 'maternal_uncle_mothers_sisters_husband', 'Malayalam', 'ml-IN', 'Parent Generation', array['Ammaavan (cheriamma bhartav)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Cinna Naanna', 'Maternal Uncle (mother''s sister''s husband)', 'maternal_uncle_mothers_sisters_husband', 'Telugu', 'te-IN', 'Parent Generation', array['Cinna Naanna', 'Mavayya']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Maava', 'Maternal Uncle (mother''s sister''s husband)', 'maternal_uncle_mothers_sisters_husband', 'Kannada', 'kn-IN', 'Parent Generation', array['Maava', 'Mava']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mausaji', 'Maternal Uncle (mother''s sister''s husband)', 'maternal_uncle_mothers_sisters_husband', 'Hindi', 'hi-IN', 'Parent Generation', array['Mausaji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aṇṇaṉ', 'Elder Brother', 'elder_brother', 'Tamil', 'ta-IN', 'Own Generation', array['Aṇṇaṉ', 'Anna']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chetan', 'Elder Brother', 'elder_brother', 'Malayalam', 'ml-IN', 'Own Generation', array['Chetan', 'Etan', 'Annan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Anna', 'Elder Brother', 'elder_brother', 'Telugu', 'te-IN', 'Own Generation', array['Anna', 'Abbāyi (elder)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Anna', 'Elder Brother', 'elder_brother', 'Kannada', 'kn-IN', 'Own Generation', array['Anna', 'Tamma (elder)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhaiyya', 'Elder Brother', 'elder_brother', 'Hindi', 'hi-IN', 'Own Generation', array['Bhaiyya', 'Bhai', 'Dada']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tampi', 'Younger Brother', 'younger_brother', 'Tamil', 'ta-IN', 'Own Generation', array['Tampi', 'Tambian']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aniyattan', 'Younger Brother', 'younger_brother', 'Malayalam', 'ml-IN', 'Own Generation', array['Aniyattan', 'Ikka']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tammudu', 'Younger Brother', 'younger_brother', 'Telugu', 'te-IN', 'Own Generation', array['Tammudu', 'Thammudu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tamma', 'Younger Brother', 'younger_brother', 'Kannada', 'kn-IN', 'Own Generation', array['Tamma', 'Anna (younger)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chota Bhai', 'Younger Brother', 'younger_brother', 'Hindi', 'hi-IN', 'Own Generation', array['Chota Bhai', 'Bhai']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka', 'Elder Sister', 'elder_sister', 'Tamil', 'ta-IN', 'Own Generation', array['Akka', 'Anni']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chechi', 'Elder Sister', 'elder_sister', 'Malayalam', 'ml-IN', 'Own Generation', array['Chechi', 'Cheche']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka', 'Elder Sister', 'elder_sister', 'Telugu', 'te-IN', 'Own Generation', array['Akka', 'Didi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka', 'Elder Sister', 'elder_sister', 'Kannada', 'kn-IN', 'Own Generation', array['Akka']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Didi', 'Elder Sister', 'elder_sister', 'Hindi', 'hi-IN', 'Own Generation', array['Didi', 'Aapa', 'Behen']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Taṅkai', 'Younger Sister', 'younger_sister', 'Tamil', 'ta-IN', 'Own Generation', array['Taṅkai', 'Tangi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aniyathi', 'Younger Sister', 'younger_sister', 'Malayalam', 'ml-IN', 'Own Generation', array['Aniyathi', 'Kutty']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chellelu', 'Younger Sister', 'younger_sister', 'Telugu', 'te-IN', 'Own Generation', array['Chellelu', 'Chelli']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Thangi', 'Younger Sister', 'younger_sister', 'Kannada', 'kn-IN', 'Own Generation', array['Thangi', 'Tayi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Choti Behen', 'Younger Sister', 'younger_sister', 'Hindi', 'hi-IN', 'Own Generation', array['Choti Behen', 'Behen']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aṇṇan (chittappa paiyan)', 'Male Cousin (paternal, elder)', 'male_cousin_paternal_elder', 'Tamil', 'ta-IN', 'Own Generation', array['Aṇṇan (chittappa paiyan)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chechi makan (appante)', 'Male Cousin (paternal, elder)', 'male_cousin_paternal_elder', 'Malayalam', 'ml-IN', 'Own Generation', array['Chechi makan (appante)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Abbayi (Pedda Naanna koduku)', 'Male Cousin (paternal, elder)', 'male_cousin_paternal_elder', 'Telugu', 'te-IN', 'Own Generation', array['Abbayi (Pedda Naanna koduku)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Dodda appa maganu', 'Male Cousin (paternal, elder)', 'male_cousin_paternal_elder', 'Kannada', 'kn-IN', 'Own Generation', array['Dodda appa maganu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Tauji ka beta', 'Male Cousin (paternal, elder)', 'male_cousin_paternal_elder', 'Hindi', 'hi-IN', 'Own Generation', array['Tauji ka beta', 'Chacha ka beta']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka (chittappa magal)', 'Female Cousin (paternal, elder)', 'female_cousin_paternal_elder', 'Tamil', 'ta-IN', 'Own Generation', array['Akka (chittappa magal)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chechi (appante)', 'Female Cousin (paternal, elder)', 'female_cousin_paternal_elder', 'Malayalam', 'ml-IN', 'Own Generation', array['Chechi (appante)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka (Pedda Naanna kuthuru)', 'Female Cousin (paternal, elder)', 'female_cousin_paternal_elder', 'Telugu', 'te-IN', 'Own Generation', array['Akka (Pedda Naanna kuthuru)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Dodda appa magaLu', 'Female Cousin (paternal, elder)', 'female_cousin_paternal_elder', 'Kannada', 'kn-IN', 'Own Generation', array['Dodda appa magaLu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Taai ki beti', 'Female Cousin (paternal, elder)', 'female_cousin_paternal_elder', 'Hindi', 'hi-IN', 'Own Generation', array['Taai ki beti', 'Bua ki beti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmā magaṉ', 'Male Cousin (maternal, elder)', 'male_cousin_maternal_elder', 'Tamil', 'ta-IN', 'Own Generation', array['Māmā magaṉ', 'Māccāṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammaavan makan', 'Male Cousin (maternal, elder)', 'male_cousin_maternal_elder', 'Malayalam', 'ml-IN', 'Own Generation', array['Ammaavan makan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmayya koduku', 'Male Cousin (maternal, elder)', 'male_cousin_maternal_elder', 'Telugu', 'te-IN', 'Own Generation', array['Māmayya koduku']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mava maganu', 'Male Cousin (maternal, elder)', 'male_cousin_maternal_elder', 'Kannada', 'kn-IN', 'Own Generation', array['Mava maganu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mama ka beta', 'Male Cousin (maternal, elder)', 'male_cousin_maternal_elder', 'Hindi', 'hi-IN', 'Own Generation', array['Mama ka beta']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmā magal', 'Female Cousin (maternal, elder)', 'female_cousin_maternal_elder', 'Tamil', 'ta-IN', 'Own Generation', array['Māmā magal']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ammaavan molu', 'Female Cousin (maternal, elder)', 'female_cousin_maternal_elder', 'Malayalam', 'ml-IN', 'Own Generation', array['Ammaavan molu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māmayya kuthuru', 'Female Cousin (maternal, elder)', 'female_cousin_maternal_elder', 'Telugu', 'te-IN', 'Own Generation', array['Māmayya kuthuru']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mava magaLu', 'Female Cousin (maternal, elder)', 'female_cousin_maternal_elder', 'Kannada', 'kn-IN', 'Own Generation', array['Mava magaLu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mama ki beti', 'Female Cousin (maternal, elder)', 'female_cousin_maternal_elder', 'Hindi', 'hi-IN', 'Own Generation', array['Mama ki beti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māppiḷḷai', 'Brother-in-law (sister''s husband)', 'brother_in_law_sisters_husband', 'Tamil', 'ta-IN', 'Own Generation', array['Māppiḷḷai', 'Macchan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('ALiyar', 'Brother-in-law (sister''s husband)', 'brother_in_law_sisters_husband', 'Malayalam', 'ml-IN', 'Own Generation', array['ALiyar', 'Bhartav']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bāvagāru', 'Brother-in-law (sister''s husband)', 'brother_in_law_sisters_husband', 'Telugu', 'te-IN', 'Own Generation', array['Bāvagāru', 'Maidunu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhava', 'Brother-in-law (sister''s husband)', 'brother_in_law_sisters_husband', 'Kannada', 'kn-IN', 'Own Generation', array['Bhava', 'ALiya']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Jijaji', 'Brother-in-law (sister''s husband)', 'brother_in_law_sisters_husband', 'Hindi', 'hi-IN', 'Own Generation', array['Jijaji', 'Bhaisaab']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māccāni', 'Sister-in-law (brother''s wife)', 'sister_in_law_brothers_wife', 'Tamil', 'ta-IN', 'Own Generation', array['Māccāni', 'Anni']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bharyavu', 'Sister-in-law (brother''s wife)', 'sister_in_law_brothers_wife', 'Malayalam', 'ml-IN', 'Own Generation', array['Bharyavu', 'Anni']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Vadina', 'Sister-in-law (brother''s wife)', 'sister_in_law_brothers_wife', 'Telugu', 'te-IN', 'Own Generation', array['Vadina', 'Maradalu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Vadini', 'Sister-in-law (brother''s wife)', 'sister_in_law_brothers_wife', 'Kannada', 'kn-IN', 'Own Generation', array['Vadini', 'ANNana hendati']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhabhi', 'Sister-in-law (brother''s wife)', 'sister_in_law_brothers_wife', 'Hindi', 'hi-IN', 'Own Generation', array['Bhabhi', 'Bhabi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māccāṉ', 'Brother-in-law (wife''s/husband''s brother)', 'brother_in_law_wifes_husbands_brother', 'Tamil', 'ta-IN', 'Own Generation', array['Māccāṉ', 'Kuḷḷantai']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhavaan', 'Brother-in-law (wife''s/husband''s brother)', 'brother_in_law_wifes_husbands_brother', 'Malayalam', 'ml-IN', 'Own Generation', array['Bhavaan', 'Ammaavani makan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mārdālu', 'Brother-in-law (wife''s/husband''s brother)', 'brother_in_law_wifes_husbands_brother', 'Telugu', 'te-IN', 'Own Generation', array['Mārdālu', 'Bāvagāru']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Maava', 'Brother-in-law (wife''s/husband''s brother)', 'brother_in_law_wifes_husbands_brother', 'Kannada', 'kn-IN', 'Own Generation', array['Maava', 'Bhava']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Devar (younger)', 'Brother-in-law (wife''s/husband''s brother)', 'brother_in_law_wifes_husbands_brother', 'Hindi', 'hi-IN', 'Own Generation', array['Devar (younger)', 'Jeth (elder)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māccāni', 'Sister-in-law (wife''s/husband''s sister)', 'sister_in_law_wifes_husbands_sister', 'Tamil', 'ta-IN', 'Own Generation', array['Māccāni', 'Aṭṭai']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Nanand', 'Sister-in-law (wife''s/husband''s sister)', 'sister_in_law_wifes_husbands_sister', 'Malayalam', 'ml-IN', 'Own Generation', array['Nanand', 'Bhaasurathi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Maradalu', 'Sister-in-law (wife''s/husband''s sister)', 'sister_in_law_wifes_husbands_sister', 'Telugu', 'te-IN', 'Own Generation', array['Maradalu', 'Naathenamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Naadini', 'Sister-in-law (wife''s/husband''s sister)', 'sister_in_law_wifes_husbands_sister', 'Kannada', 'kn-IN', 'Own Generation', array['Naadini', 'Maradaalu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Nanad (husband''s sis)', 'Sister-in-law (wife''s/husband''s sister)', 'sister_in_law_wifes_husbands_sister', 'Hindi', 'hi-IN', 'Own Generation', array['Nanad (husband''s sis)', 'Saali (wife''s sis)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Kaṇavaṉ', 'Husband', 'husband', 'Tamil', 'ta-IN', 'Spouse & In-Laws', array['Kaṇavaṉ', 'Nātar']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhartav', 'Husband', 'husband', 'Malayalam', 'ml-IN', 'Spouse & In-Laws', array['Bhartav', 'Pennin bhartav']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māripidi', 'Husband', 'husband', 'Telugu', 'te-IN', 'Spouse & In-Laws', array['Māripidi', 'Bharta']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Ganda', 'Husband', 'husband', 'Kannada', 'kn-IN', 'Spouse & In-Laws', array['Ganda', 'Husband']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pati', 'Husband', 'husband', 'Hindi', 'hi-IN', 'Spouse & In-Laws', array['Pati', 'Shohar']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Maṉaivi', 'Wife', 'wife', 'Tamil', 'ta-IN', 'Spouse & In-Laws', array['Maṉaivi', 'Manam']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bharya', 'Wife', 'wife', 'Malayalam', 'ml-IN', 'Spouse & In-Laws', array['Bharya', 'Penn']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhārya', 'Wife', 'wife', 'Telugu', 'te-IN', 'Spouse & In-Laws', array['Bhārya', 'Pellam']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Hendati', 'Wife', 'wife', 'Kannada', 'kn-IN', 'Spouse & In-Laws', array['Hendati', 'Beli']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Patni', 'Wife', 'wife', 'Hindi', 'hi-IN', 'Spouse & In-Laws', array['Patni', 'Biwi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumagaṉ Appā', 'Father-in-law', 'father_in_law', 'Tamil', 'ta-IN', 'Spouse & In-Laws', array['Marumagaṉ Appā', 'Mamaṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Appan', 'Father-in-law', 'father_in_law', 'Malayalam', 'ml-IN', 'Spouse & In-Laws', array['Appan', 'Shvasuran']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Māvagāru', 'Father-in-law', 'father_in_law', 'Telugu', 'te-IN', 'Spouse & In-Laws', array['Māvagāru', 'Mamma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mava', 'Father-in-law', 'father_in_law', 'Kannada', 'kn-IN', 'Spouse & In-Laws', array['Mava', 'Maava']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Sasur', 'Father-in-law', 'father_in_law', 'Hindi', 'hi-IN', 'Spouse & In-Laws', array['Sasur', 'Susarji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumagal Ammā', 'Mother-in-law', 'mother_in_law', 'Tamil', 'ta-IN', 'Spouse & In-Laws', array['Marumagal Ammā', 'Mamaṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Amma', 'Mother-in-law', 'mother_in_law', 'Malayalam', 'ml-IN', 'Spouse & In-Laws', array['Amma', 'Shvasru']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Attagāru', 'Mother-in-law', 'mother_in_law', 'Telugu', 'te-IN', 'Spouse & In-Laws', array['Attagāru', 'Atha']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Atte', 'Mother-in-law', 'mother_in_law', 'Kannada', 'kn-IN', 'Spouse & In-Laws', array['Atte', 'Attheyavaru']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Saas', 'Mother-in-law', 'mother_in_law', 'Hindi', 'hi-IN', 'Spouse & In-Laws', array['Saas', 'Saasuma']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumagaṉ', 'Son-in-law', 'son_in_law', 'Tamil', 'ta-IN', 'Spouse & In-Laws', array['Marumagaṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aḷiyar', 'Son-in-law', 'son_in_law', 'Malayalam', 'ml-IN', 'Spouse & In-Laws', array['Aḷiyar']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Abbayi', 'Son-in-law', 'son_in_law', 'Telugu', 'te-IN', 'Spouse & In-Laws', array['Abbayi', 'Alludu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Aliya', 'Son-in-law', 'son_in_law', 'Kannada', 'kn-IN', 'Spouse & In-Laws', array['Aliya', 'Marumaganu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Damad', 'Son-in-law', 'son_in_law', 'Hindi', 'hi-IN', 'Spouse & In-Laws', array['Damad', 'Jamai']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumagal', 'Daughter-in-law', 'daughter_in_law', 'Tamil', 'ta-IN', 'Spouse & In-Laws', array['Marumagal']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumagal', 'Daughter-in-law', 'daughter_in_law', 'Malayalam', 'ml-IN', 'Spouse & In-Laws', array['Marumagal']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Kodallu', 'Daughter-in-law', 'daughter_in_law', 'Telugu', 'te-IN', 'Spouse & In-Laws', array['Kodallu', 'Kallu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Sose', 'Daughter-in-law', 'daughter_in_law', 'Kannada', 'kn-IN', 'Spouse & In-Laws', array['Sose', 'Marumagaḷu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bahu', 'Daughter-in-law', 'daughter_in_law', 'Hindi', 'hi-IN', 'Spouse & In-Laws', array['Bahu', 'Patohoo']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Makaṉ', 'Son', 'son', 'Tamil', 'ta-IN', 'Child Generation', array['Makaṉ', 'Paiyan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Makan', 'Son', 'son', 'Malayalam', 'ml-IN', 'Child Generation', array['Makan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Koduku', 'Son', 'son', 'Telugu', 'te-IN', 'Child Generation', array['Koduku', 'Abbayi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Maganu', 'Son', 'son', 'Kannada', 'kn-IN', 'Child Generation', array['Maganu', 'Maga']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Beta', 'Son', 'son', 'Hindi', 'hi-IN', 'Child Generation', array['Beta', 'Putra', 'Ladka']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Magal', 'Daughter', 'daughter', 'Tamil', 'ta-IN', 'Child Generation', array['Magal', 'Penu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mol', 'Daughter', 'daughter', 'Malayalam', 'ml-IN', 'Child Generation', array['Mol', 'Molu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Kuthuru', 'Daughter', 'daughter', 'Telugu', 'te-IN', 'Child Generation', array['Kuthuru', 'Ammayi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('MagaLu', 'Daughter', 'daughter', 'Kannada', 'kn-IN', 'Child Generation', array['MagaLu', 'Magaḷu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Beti', 'Daughter', 'daughter', 'Hindi', 'hi-IN', 'Child Generation', array['Beti', 'Ladki', 'Putri']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumakaṉ', 'Nephew (brother''s son)', 'nephew_brothers_son', 'Tamil', 'ta-IN', 'Child Generation', array['Marumakaṉ', 'Aṇṇan makaṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Annan makan', 'Nephew (brother''s son)', 'nephew_brothers_son', 'Malayalam', 'ml-IN', 'Child Generation', array['Annan makan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Alludi', 'Nephew (brother''s son)', 'nephew_brothers_son', 'Telugu', 'te-IN', 'Child Generation', array['Alludi', 'Anna koduku']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Anna', 'Nephew (brother''s son)', 'nephew_brothers_son', 'Kannada', 'kn-IN', 'Child Generation', array['Anna', 'Tamma maganu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhatija', 'Nephew (brother''s son)', 'nephew_brothers_son', 'Hindi', 'hi-IN', 'Child Generation', array['Bhatija']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumakkal', 'Niece (brother''s daughter)', 'niece_brothers_daughter', 'Tamil', 'ta-IN', 'Child Generation', array['Marumakkal', 'Aṇṇan magal']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Annan mol', 'Niece (brother''s daughter)', 'niece_brothers_daughter', 'Malayalam', 'ml-IN', 'Child Generation', array['Annan mol']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Alludannu', 'Niece (brother''s daughter)', 'niece_brothers_daughter', 'Telugu', 'te-IN', 'Child Generation', array['Alludannu', 'Anna kuthuru']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Anna', 'Niece (brother''s daughter)', 'niece_brothers_daughter', 'Kannada', 'kn-IN', 'Child Generation', array['Anna', 'Tamma magaLu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhatiji', 'Niece (brother''s daughter)', 'niece_brothers_daughter', 'Hindi', 'hi-IN', 'Child Generation', array['Bhatiji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumakaṉ (akka makaṉ)', 'Nephew (sister''s son)', 'nephew_sisters_son', 'Tamil', 'ta-IN', 'Child Generation', array['Marumakaṉ (akka makaṉ)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chechi makan', 'Nephew (sister''s son)', 'nephew_sisters_son', 'Malayalam', 'ml-IN', 'Child Generation', array['Chechi makan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka koduku', 'Nephew (sister''s son)', 'nephew_sisters_son', 'Telugu', 'te-IN', 'Child Generation', array['Akka koduku']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka maganu', 'Nephew (sister''s son)', 'nephew_sisters_son', 'Kannada', 'kn-IN', 'Child Generation', array['Akka maganu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhanja', 'Nephew (sister''s son)', 'nephew_sisters_son', 'Hindi', 'hi-IN', 'Child Generation', array['Bhanja']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Marumagal (akka magal)', 'Niece (sister''s daughter)', 'niece_sisters_daughter', 'Tamil', 'ta-IN', 'Child Generation', array['Marumagal (akka magal)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Chechi mol', 'Niece (sister''s daughter)', 'niece_sisters_daughter', 'Malayalam', 'ml-IN', 'Child Generation', array['Chechi mol']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka kuthuru', 'Niece (sister''s daughter)', 'niece_sisters_daughter', 'Telugu', 'te-IN', 'Child Generation', array['Akka kuthuru']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Akka magaLu', 'Niece (sister''s daughter)', 'niece_sisters_daughter', 'Kannada', 'kn-IN', 'Child Generation', array['Akka magaLu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Bhanji', 'Niece (sister''s daughter)', 'niece_sisters_daughter', 'Hindi', 'hi-IN', 'Child Generation', array['Bhanji']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Peraṉ', 'Grandson (son''s son)', 'grandson_sons_son', 'Tamil', 'ta-IN', 'Child Generation', array['Peraṉ', 'Pēraṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Perappattu', 'Grandson (son''s son)', 'grandson_sons_son', 'Malayalam', 'ml-IN', 'Child Generation', array['Perappattu', 'Makante makan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Manavadu', 'Grandson (son''s son)', 'grandson_sons_son', 'Telugu', 'te-IN', 'Child Generation', array['Manavadu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mommaga', 'Grandson (son''s son)', 'grandson_sons_son', 'Kannada', 'kn-IN', 'Child Generation', array['Mommaga', 'Moddukavanu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pota', 'Grandson (son''s son)', 'grandson_sons_son', 'Hindi', 'hi-IN', 'Child Generation', array['Pota']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Peṭṭi', 'Granddaughter (son''s daughter)', 'granddaughter_sons_daughter', 'Tamil', 'ta-IN', 'Child Generation', array['Peṭṭi', 'Pētti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Makante mol', 'Granddaughter (son''s daughter)', 'granddaughter_sons_daughter', 'Malayalam', 'ml-IN', 'Child Generation', array['Makante mol']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Manavaralu', 'Granddaughter (son''s daughter)', 'granddaughter_sons_daughter', 'Telugu', 'te-IN', 'Child Generation', array['Manavaralu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mommaga (female)', 'Granddaughter (son''s daughter)', 'granddaughter_sons_daughter', 'Kannada', 'kn-IN', 'Child Generation', array['Mommaga (female)']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Poti', 'Granddaughter (son''s daughter)', 'granddaughter_sons_daughter', 'Hindi', 'hi-IN', 'Child Generation', array['Poti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mākkaḷ makaṉ', 'Grandson (daughter''s son)', 'grandson_daughters_son', 'Tamil', 'ta-IN', 'Child Generation', array['Mākkaḷ makaṉ']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Molute makan', 'Grandson (daughter''s son)', 'grandson_daughters_son', 'Malayalam', 'ml-IN', 'Child Generation', array['Molute makan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Kuthuru koduku', 'Grandson (daughter''s son)', 'grandson_daughters_son', 'Telugu', 'te-IN', 'Child Generation', array['Kuthuru koduku']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('MagaLu maganu', 'Grandson (daughter''s son)', 'grandson_daughters_son', 'Kannada', 'kn-IN', 'Child Generation', array['MagaLu maganu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Navasa', 'Grandson (daughter''s son)', 'grandson_daughters_son', 'Hindi', 'hi-IN', 'Child Generation', array['Navasa', 'Dohita']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Mākkaḷ magal', 'Granddaughter (daughter''s daughter)', 'granddaughter_daughters_daughter', 'Tamil', 'ta-IN', 'Child Generation', array['Mākkaḷ magal']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Molute mol', 'Granddaughter (daughter''s daughter)', 'granddaughter_daughters_daughter', 'Malayalam', 'ml-IN', 'Child Generation', array['Molute mol']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Kuthuru kuthuru', 'Granddaughter (daughter''s daughter)', 'granddaughter_daughters_daughter', 'Telugu', 'te-IN', 'Child Generation', array['Kuthuru kuthuru']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('MagaLu magaLu', 'Granddaughter (daughter''s daughter)', 'granddaughter_daughters_daughter', 'Kannada', 'kn-IN', 'Child Generation', array['MagaLu magaLu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Navasi', 'Granddaughter (daughter''s daughter)', 'granddaughter_daughters_daughter', 'Hindi', 'hi-IN', 'Child Generation', array['Navasi', 'Dohiti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Koṟṟan', 'Great-grandson', 'great_grandson', 'Tamil', 'ta-IN', 'Child Generation', array['Koṟṟan', 'Kūṟṟan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Kochu makan', 'Great-grandson', 'great_grandson', 'Malayalam', 'ml-IN', 'Child Generation', array['Kochu makan', 'peran makan']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Peddha Manavarālu', 'Great-grandson', 'great_grandson', 'Telugu', 'te-IN', 'Child Generation', array['Peddha Manavarālu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Moddukavanu maga', 'Great-grandson', 'great_grandson', 'Kannada', 'kn-IN', 'Child Generation', array['Moddukavanu maga']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pardota', 'Great-grandson', 'great_grandson', 'Hindi', 'hi-IN', 'Child Generation', array['Pardota']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Koṟṟi', 'Great-granddaughter', 'great_granddaughter', 'Tamil', 'ta-IN', 'Child Generation', array['Koṟṟi']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Kochu mol', 'Great-granddaughter', 'great_granddaughter', 'Malayalam', 'ml-IN', 'Child Generation', array['Kochu mol', 'peran mol']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pedda Manavari', 'Great-granddaughter', 'great_granddaughter', 'Telugu', 'te-IN', 'Child Generation', array['Pedda Manavari']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Moddukavanu magaLu', 'Great-granddaughter', 'great_granddaughter', 'Kannada', 'kn-IN', 'Child Generation', array['Moddukavanu magaLu']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook'),
  ('Pardoti', 'Great-granddaughter', 'great_granddaughter', 'Hindi', 'hi-IN', 'Child Generation', array['Pardoti']::text[], 'Family_Relationship_Words-languages.numbers', 'workbook')
on conflict (canonical_code, language_tag, term)
do update set
  canonical_meaning = excluded.canonical_meaning,
  language = excluded.language,
  generation = excluded.generation,
  variants = excluded.variants,
  source_name = excluded.source_name,
  source_type = excluded.source_type,
  updated_at = now();

alter table public.relationship_terms enable row level security;

drop policy if exists "Relationship terms are readable reference data"
  on public.relationship_terms;

create policy "Relationship terms are readable reference data"
  on public.relationship_terms
  for select
  to anon, authenticated
  using (true);

revoke all on table public.relationship_terms from anon, authenticated;
grant select on table public.relationship_terms to anon, authenticated;
grant select, insert, update, delete on table public.relationship_terms
  to service_role;
