name: vansha_mobile
description: Vamsha family relationship platform
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  graphview: ^1.2.0
  flutter_animate: ^4.5.0
  supabase_flutter: ^2.12.4
  sembast: ^3.8.6
  sembast_web: ^2.4.6
  image_picker: ^1.2.4
  path_provider: ^2.1.5
  image_picker_for_web: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/relationship_terms.json
