// Generated from Family_Relationship_Words-languages.numbers.
// Do not edit terms manually; regenerate them from the source workbook.
const relationshipTermsByCode = <String, Map<String, String>>{
  'great_great_grandfather': {
    'ta-IN': 'Muppaṭṭakkārar',
    'ml-IN': 'Muttachan (avan avan appan)',
    'te-IN': 'Muddu Tāṭayya',
    'kn-IN': 'Muddajja',
    'hi-IN': 'Pardada ka baap (Pūrvaj)',
  },
  'great_great_grandmother': {
    'ta-IN': 'Muppaṭṭi',
    'ml-IN': 'Muttassi (avan avan amma)',
    'te-IN': 'Muddu Nānamma',
    'kn-IN': 'Muddajji',
    'hi-IN': 'Pardadi ki maa (Pūrvaj)',
  },
  'great_grandfather_paternal': {
    'ta-IN': 'Muppaṭṭanār',
    'ml-IN': 'Appappan',
    'te-IN': 'Pedda Tāṭayya',
    'kn-IN': 'Appa-appa',
    'hi-IN': 'Pardada',
  },
  'great_grandmother_paternal': {
    'ta-IN': 'Muppaṭṭi',
    'ml-IN': 'Appamma',
    'te-IN': 'Pedda Nānamma',
    'kn-IN': 'Appa-ajji',
    'hi-IN': 'Pardadi',
  },
  'great_grandfather_maternal': {
    'ta-IN': 'Aṇṇāttaṉ',
    'ml-IN': 'Ammaman appa',
    'te-IN': 'Ammamma Tāṭayya',
    'kn-IN': 'Tāyi-appa',
    'hi-IN': 'Nana ka baap',
  },
  'great_grandmother_maternal': {
    'ta-IN': 'Āttacci',
    'ml-IN': 'Ammumma amma',
    'te-IN': 'Ammamma Nānamma',
    'kn-IN': 'Tāyi-ajji',
    'hi-IN': 'Nani ki maa',
  },
  'grandfather_paternal': {
    'ta-IN': 'Tāttā',
    'ml-IN': 'Appappan',
    'te-IN': 'Tāṭayya (Babayya)',
    'kn-IN': 'Ajja',
    'hi-IN': 'Dada',
  },
  'grandmother_paternal': {
    'ta-IN': 'Pāṭṭi',
    'ml-IN': 'Appamma',
    'te-IN': 'Nānamma (Avva)',
    'kn-IN': 'Ajji',
    'hi-IN': 'Dadi',
  },
  'grandfather_maternal': {
    'ta-IN': 'Tāttā (tāymanai)',
    'ml-IN': 'Ammapan',
    'te-IN': 'Ammamma Tāṭayya',
    'kn-IN': 'Tāyi-ajja',
    'hi-IN': 'Nana',
  },
  'grandmother_maternal': {
    'ta-IN': 'Āttai pāṭṭi',
    'ml-IN': 'Ammumma',
    'te-IN': 'Ammamma',
    'kn-IN': 'Tāyi-ajji',
    'hi-IN': 'Nani',
  },
  'father': {
    'ta-IN': 'Appā',
    'ml-IN': 'Achan',
    'te-IN': 'Naanna',
    'kn-IN': 'Appa',
    'hi-IN': 'Pitaji',
  },
  'mother': {
    'ta-IN': 'Ammā',
    'ml-IN': 'Amma',
    'te-IN': 'Ammā',
    'kn-IN': 'Amma',
    'hi-IN': 'Maa',
  },
  'paternal_uncle_fathers_elder_brother': {
    'ta-IN': 'Periyappa',
    'ml-IN': 'Valiachhan',
    'te-IN': 'Pedda Naanna',
    'kn-IN': 'Dodda Appa',
    'hi-IN': 'Taauji',
  },
  'paternal_aunt_fathers_elder_brothers_wife': {
    'ta-IN': 'Periyamma',
    'ml-IN': 'Valiaamma',
    'te-IN': 'Pedda Amma',
    'kn-IN': 'Dodda Amma',
    'hi-IN': 'Taai',
  },
  'paternal_uncle_fathers_younger_brother': {
    'ta-IN': 'Ciṭṭappa',
    'ml-IN': 'Cheriachhan',
    'te-IN': 'Cinna Naanna',
    'kn-IN': 'Chikka Appa',
    'hi-IN': 'Chacha',
  },
  'paternal_aunt_fathers_younger_bros_wife': {
    'ta-IN': 'Ciṭṭi',
    'ml-IN': 'Cheriaamma',
    'te-IN': 'Cinna Amma',
    'kn-IN': 'Chikka Amma',
    'hi-IN': 'Chachi',
  },
  'paternal_aunt_fathers_sister': {
    'ta-IN': 'Aṭṭai',
    'ml-IN': 'Appante chechi',
    'te-IN': 'Naanna Akka',
    'kn-IN': 'Atte',
    'hi-IN': 'Bua',
  },
  'paternal_uncle_fathers_sisters_husband': {
    'ta-IN': 'Aṭṭaṉ',
    'ml-IN': 'Appante chechi bhartav',
    'te-IN': 'Baava',
    'kn-IN': 'Mava',
    'hi-IN': 'Fufaji',
  },
  'maternal_uncle_mothers_brother': {
    'ta-IN': 'Māmā',
    'ml-IN': 'Ammaavan',
    'te-IN': 'Māmayya',
    'kn-IN': 'Mava',
    'hi-IN': 'Mama',
  },
  'maternal_aunt_mothers_brothers_wife': {
    'ta-IN': 'Māmi',
    'ml-IN': 'Ammaavan bharya',
    'te-IN': 'Māmamma',
    'kn-IN': 'Maami',
    'hi-IN': 'Mami',
  },
  'maternal_aunt_mothers_elder_sister': {
    'ta-IN': 'Periyamma',
    'ml-IN': 'Valiamma (ammante chechi)',
    'te-IN': 'Peddamma',
    'kn-IN': 'Dodda Amma',
    'hi-IN': 'Badi Mausi',
  },
  'maternal_aunt_mothers_younger_sister': {
    'ta-IN': 'Ciṭṭi',
    'ml-IN': 'Cheriamma (ammante aniyathi)',
    'te-IN': 'Cinna Amma',
    'kn-IN': 'Chikka Amma',
    'hi-IN': 'Mausi',
  },
  'maternal_uncle_mothers_sisters_husband': {
    'ta-IN': 'Māmā (ciṭṭappa)',
    'ml-IN': 'Ammaavan (cheriamma bhartav)',
    'te-IN': 'Cinna Naanna',
    'kn-IN': 'Maava',
    'hi-IN': 'Mausaji',
  },
  'elder_brother': {
    'ta-IN': 'Aṇṇaṉ',
    'ml-IN': 'Chetan',
    'te-IN': 'Anna',
    'kn-IN': 'Anna',
    'hi-IN': 'Bhaiyya',
  },
  'younger_brother': {
    'ta-IN': 'Tampi',
    'ml-IN': 'Aniyattan',
    'te-IN': 'Tammudu',
    'kn-IN': 'Tamma',
    'hi-IN': 'Chota Bhai',
  },
  'elder_sister': {
    'ta-IN': 'Akka',
    'ml-IN': 'Chechi',
    'te-IN': 'Akka',
    'kn-IN': 'Akka',
    'hi-IN': 'Didi',
  },
  'younger_sister': {
    'ta-IN': 'Taṅkai',
    'ml-IN': 'Aniyathi',
    'te-IN': 'Chellelu',
    'kn-IN': 'Thangi',
    'hi-IN': 'Choti Behen',
  },
  'male_cousin_paternal_elder': {
    'ta-IN': 'Aṇṇan (chittappa paiyan)',
    'ml-IN': 'Chechi makan (appante)',
    'te-IN': 'Abbayi (Pedda Naanna koduku)',
    'kn-IN': 'Dodda appa maganu',
    'hi-IN': 'Tauji ka beta',
  },
  'female_cousin_paternal_elder': {
    'ta-IN': 'Akka (chittappa magal)',
    'ml-IN': 'Chechi (appante)',
    'te-IN': 'Akka (Pedda Naanna kuthuru)',
    'kn-IN': 'Dodda appa magaLu',
    'hi-IN': 'Taai ki beti',
  },
  'male_cousin_maternal_elder': {
    'ta-IN': 'Māmā magaṉ',
    'ml-IN': 'Ammaavan makan',
    'te-IN': 'Māmayya koduku',
    'kn-IN': 'Mava maganu',
    'hi-IN': 'Mama ka beta',
  },
  'female_cousin_maternal_elder': {
    'ta-IN': 'Māmā magal',
    'ml-IN': 'Ammaavan molu',
    'te-IN': 'Māmayya kuthuru',
    'kn-IN': 'Mava magaLu',
    'hi-IN': 'Mama ki beti',
  },
  'brother_in_law_sisters_husband': {
    'ta-IN': 'Māppiḷḷai',
    'ml-IN': 'ALiyar',
    'te-IN': 'Bāvagāru',
    'kn-IN': 'Bhava',
    'hi-IN': 'Jijaji',
  },
  'sister_in_law_brothers_wife': {
    'ta-IN': 'Māccāni',
    'ml-IN': 'Bharyavu',
    'te-IN': 'Vadina',
    'kn-IN': 'Vadini',
    'hi-IN': 'Bhabhi',
  },
  'brother_in_law_wifes_husbands_brother': {
    'ta-IN': 'Māccāṉ',
    'ml-IN': 'Bhavaan',
    'te-IN': 'Mārdālu',
    'kn-IN': 'Maava',
    'hi-IN': 'Devar (younger)',
  },
  'sister_in_law_wifes_husbands_sister': {
    'ta-IN': 'Māccāni',
    'ml-IN': 'Nanand',
    'te-IN': 'Maradalu',
    'kn-IN': 'Naadini',
    'hi-IN': 'Nanad (husband\'s sis)',
  },
  'husband': {
    'ta-IN': 'Kaṇavaṉ',
    'ml-IN': 'Bhartav',
    'te-IN': 'Māripidi',
    'kn-IN': 'Ganda',
    'hi-IN': 'Pati',
  },
  'wife': {
    'ta-IN': 'Maṉaivi',
    'ml-IN': 'Bharya',
    'te-IN': 'Bhārya',
    'kn-IN': 'Hendati',
    'hi-IN': 'Patni',
  },
  'father_in_law': {
    'ta-IN': 'Marumagaṉ Appā',
    'ml-IN': 'Appan',
    'te-IN': 'Māvagāru',
    'kn-IN': 'Mava',
    'hi-IN': 'Sasur',
  },
  'mother_in_law': {
    'ta-IN': 'Marumagal Ammā',
    'ml-IN': 'Amma',
    'te-IN': 'Attagāru',
    'kn-IN': 'Atte',
    'hi-IN': 'Saas',
  },
  'son_in_law': {
    'ta-IN': 'Marumagaṉ',
    'ml-IN': 'Aḷiyar',
    'te-IN': 'Abbayi',
    'kn-IN': 'Aliya',
    'hi-IN': 'Damad',
  },
  'daughter_in_law': {
    'ta-IN': 'Marumagal',
    'ml-IN': 'Marumagal',
    'te-IN': 'Kodallu',
    'kn-IN': 'Sose',
    'hi-IN': 'Bahu',
  },
  'son': {
    'ta-IN': 'Makaṉ',
    'ml-IN': 'Makan',
    'te-IN': 'Koduku',
    'kn-IN': 'Maganu',
    'hi-IN': 'Beta',
  },
  'daughter': {
    'ta-IN': 'Magal',
    'ml-IN': 'Mol',
    'te-IN': 'Kuthuru',
    'kn-IN': 'MagaLu',
    'hi-IN': 'Beti',
  },
  'nephew_brothers_son': {
    'ta-IN': 'Marumakaṉ',
    'ml-IN': 'Annan makan',
    'te-IN': 'Alludi',
    'kn-IN': 'Anna',
    'hi-IN': 'Bhatija',
  },
  'niece_brothers_daughter': {
    'ta-IN': 'Marumakkal',
    'ml-IN': 'Annan mol',
    'te-IN': 'Alludannu',
    'kn-IN': 'Anna',
    'hi-IN': 'Bhatiji',
  },
  'nephew_sisters_son': {
    'ta-IN': 'Marumakaṉ (akka makaṉ)',
    'ml-IN': 'Chechi makan',
    'te-IN': 'Akka koduku',
    'kn-IN': 'Akka maganu',
    'hi-IN': 'Bhanja',
  },
  'niece_sisters_daughter': {
    'ta-IN': 'Marumagal (akka magal)',
    'ml-IN': 'Chechi mol',
    'te-IN': 'Akka kuthuru',
    'kn-IN': 'Akka magaLu',
    'hi-IN': 'Bhanji',
  },
  'grandson_sons_son': {
    'ta-IN': 'Peraṉ',
    'ml-IN': 'Perappattu',
    'te-IN': 'Manavarālu',
    'kn-IN': 'Mommaga',
    'hi-IN': 'Pota',
  },
  'granddaughter_sons_daughter': {
    'ta-IN': 'Peṭṭi',
    'ml-IN': 'Makante mol',
    'te-IN': 'Manavarālu (female)',
    'kn-IN': 'Mommaga (female)',
    'hi-IN': 'Poti',
  },
  'grandson_daughters_son': {
    'ta-IN': 'Mākkaḷ makaṉ',
    'ml-IN': 'Molute makan',
    'te-IN': 'Kuthuru koduku',
    'kn-IN': 'MagaLu maganu',
    'hi-IN': 'Navasa',
  },
  'granddaughter_daughters_daughter': {
    'ta-IN': 'Mākkaḷ magal',
    'ml-IN': 'Molute mol',
    'te-IN': 'Kuthuru kuthuru',
    'kn-IN': 'MagaLu magaLu',
    'hi-IN': 'Navasi',
  },
  'great_grandson': {
    'ta-IN': 'Koṟṟan',
    'ml-IN': 'Kochu makan',
    'te-IN': 'Peddha Manavarālu',
    'kn-IN': 'Moddukavanu maga',
    'hi-IN': 'Pardota',
  },
  'great_granddaughter': {
    'ta-IN': 'Koṟṟi',
    'ml-IN': 'Kochu mol',
    'te-IN': 'Pedda Manavari',
    'kn-IN': 'Moddukavanu magaLu',
    'hi-IN': 'Pardoti',
  },
};
